# Generated by Django 6.0.5 on 2026-05-13 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(choices=[('epic', 'Epic'), ('story', 'Story'), ('task', 'Task'), ('bug', 'Bug'), ('subtask', 'Subtask')], max_length=16)),
                ('icon', models.CharField(default='✷', max_length=8)),
                ('color', models.CharField(default='#1e6fff', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(default='#1e6fff', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('weight', models.IntegerField(default=0, help_text='Higher = more urgent')),
                ('color', models.CharField(default='#1e6fff', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'priorities',
                'ordering': ('-weight',),
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=30, unique=True)),
                ('summary', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('story_points', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('estimate_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('time_remaining_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank', models.FloatField(default=0, help_text='Used for board ordering')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('epic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.epic')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='issues.issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_issues', to=settings.AUTH_USER_MODEL)),
                ('sprint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects.sprint')),
                ('watchers', models.ManyToManyField(blank=True, related_name='watched_issues', to=settings.AUTH_USER_MODEL)),
                ('issue_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.issuetype')),
                ('labels', models.ManyToManyField(blank=True, related_name='issues', to='issues.label')),
                ('priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.priority')),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='HistoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=40)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='issues.issue')),
            ],
            options={
                'verbose_name_plural': 'history entries',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('edited', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='issues.issue')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=255)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=120)),
                ('size', models.PositiveIntegerField(default=0, help_text='Raw bytes before base64.')),
                ('data', models.TextField(default='', help_text='Base64-encoded file contents.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='issues.issue')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('category', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], max_length=16)),
                ('order', models.PositiveIntegerField(default=0)),
                ('allowed_next', models.ManyToManyField(blank=True, related_name='reachable_from', to='issues.status')),
            ],
            options={
                'verbose_name_plural': 'statuses',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='issues.status'),
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveIntegerField()),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='issues.issue')),
            ],
            options={
                'ordering': ('-logged_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=40)),
                ('target_type', models.CharField(help_text='Model name, e.g. issue/comment/sprint.', max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'audit entries',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['project', '-created_at'], name='issues_audi_project_7c04c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='IssueLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('blocks', 'bloquea'), ('blocked_by', 'bloqueado por'), ('relates_to', 'relacionado con'), ('duplicates', 'duplica'), ('duplicated_by', 'duplicado por')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_out', to='issues.issue')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_in', to='issues.issue')),
            ],
            options={
                'ordering': ('type', 'id'),
                'unique_together': {('source', 'target', 'type')},
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status'], name='issues_issu_project_3c2b84_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assignee'], name='issues_issu_assigne_32a375_idx'),
        ),
    ]
