# Generated by Django 6.0.5 on 2026-05-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file',
        ),
        migrations.AddField(
            model_name='attachment',
            name='content_type',
            field=models.CharField(default='application/octet-stream', max_length=120),
        ),
        migrations.AddField(
            model_name='attachment',
            name='data',
            field=models.TextField(default='', help_text='Base64-encoded file contents.'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size',
            field=models.PositiveIntegerField(default=0, help_text='Raw bytes before base64.'),
        ),
    ]
