# Generated by Django 6.0.5 on 2026-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='body_html_cache',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='description_html_cache',
            field=models.TextField(blank=True, default=''),
        ),
    ]
