# Generated by Django 6.0.5 on 2026-05-15 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-archived after configured retention; hidden from default views.'),
        ),
        migrations.CreateModel(
            name='CommentEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_body', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edits', to='issues.comment')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-edited_at',),
            },
        ),
        migrations.CreateModel(
            name='BranchLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(max_length=200)),
                ('repo_url', models.URLField(blank=True)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='issues.issue')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('issue', 'branch', 'commit_sha')},
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('+1', '👍'), ('-1', '👎'), ('heart', '❤️'), ('tada', '🎉'), ('eyes', '👀'), ('rocket', '🚀')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='issues.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'emoji'], name='issues_reac_comment_712adf_idx')],
                'unique_together': {('comment', 'user', 'emoji')},
            },
        ),
    ]
