# Generated by Django 6.0.5 on 2026-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='retro_notes',
            field=models.TextField(blank=True, default='', help_text='Notas de retrospectiva: qué fue bien, qué mejorar.'),
        ),
    ]
