# Generated by Django 6.0.5 on 2026-05-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectwiki'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='events',
        ),
        migrations.AddField(
            model_name='webhook',
            name='entity',
            field=models.CharField(default='issue', help_text='What kind of object triggers this hook (issue/epic/comment).', max_length=32),
        ),
        migrations.AddField(
            model_name='webhook',
            name='event',
            field=models.CharField(default='issue.updated', help_text='Event code from the webhook registry.', max_length=64),
        ),
        migrations.AddField(
            model_name='webhook',
            name='state_filter',
            field=models.CharField(blank=True, help_text='Comma-separated state names. Empty = fire on any state.', max_length=255),
        ),
    ]
