# Generated by Django 6.0.5 on 2026-05-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_webhook_events_webhook_entity_webhook_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhook',
            name='secret',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='url',
        ),
        migrations.AddField(
            model_name='webhook',
            name='action',
            field=models.CharField(default='', help_text='Action code from the in-process webhook-action registry.', max_length=120),
        ),
    ]
