# Generated by Django 6.0.5 on 2026-05-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, default='', help_text='Avatar codificado en base64 como data URL (data:image/...;base64,...).'),
        ),
    ]
