# Generated by Django 6.0.5 on 2026-05-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_apikey_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='palette',
            field=models.CharField(default='blue', help_text='Paleta de colores aplicada al renderizar la UI.', max_length=20),
        ),
    ]
