# Generated by Django 6.0.5 on 2026-05-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='muted_kinds',
            field=models.CharField(blank=True, default='', help_text='Tipos de notificación silenciados (separados por comas).', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Recibir correos. Si está desactivado, sólo verás avisos en la app.'),
        ),
    ]
