# Generated by Django 6.0.5 on 2026-05-15 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_muted_kinds_user_notify_email'),
        ('issues', '0004_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_made', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mention_receipts', to='issues.comment')),
                ('mentioned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['mentioned', 'seen_at'], name='accounts_me_mention_983a83_idx')],
                'unique_together': {('mentioned', 'comment')},
            },
        ),
    ]
