# Generated by Django 6.0.5 on 2026-05-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_team_dashboardwidget'),
    ]

    def _backfill(apps, schema_editor):
        """Seed ``unread_count`` from the source-of-truth Notification rows."""
        Notification = apps.get_model("accounts", "Notification")
        User = apps.get_model("accounts", "User")
        from django.db.models import Count
        counts = dict(
            Notification.objects.filter(read=False)
            .values_list("recipient_id")
            .annotate(c=Count("id"))
            .values_list("recipient_id", "c")
        )
        for user in User.objects.iterator():
            user.unread_count = counts.get(user.pk, 0)
            user.save(update_fields=["unread_count"])

    operations = [
        migrations.AddField(
            model_name='user',
            name='unread_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(_backfill, reverse_code=migrations.RunPython.noop),
    ]
