# Generated by Django 6.0.5 on 2026-05-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_unread_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='es', help_text='Idioma de la interfaz.', max_length=8),
        ),
    ]
