# Generated by Django 6.0.5 on 2026-05-15 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_projectwiki'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBoardView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('is_default', models.BooleanField(default=False, help_text="Auto-applied when the user opens this project's board.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_views', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['user', 'project'], name='board_saved_user_id_37f7bf_idx')],
                'unique_together': {('user', 'project', 'name')},
            },
        ),
    ]
